# Generated by Django 4.2.14 on 2024-08-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_comment_is_acrive_comment_recommend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_acrive',
            new_name='is_active',
        ),
    ]
